project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: /src/usr/local/emhttp/plugins/auto-unlock/locales/en_US.json
    dest: /unraid-auto-unlock/en_US.json
    translation: /src/usr/local/emhttp/plugins/auto-unlock/locales/%locale_with_underscore%.json
