version: "2"
linters:
  default: all
  disable:
    - wsl # Superseded by wsl_v5
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - gochecknoinits # Required for fetcher registry
    - noctx
    - lll
    - testpackage
    - paralleltest
    - tagalign # Provided by golines
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - varnamelen
          - errcheck
          - goconst
  settings:
    varnamelen:
      ignore-decls:
        - fs afero.Fs

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
